import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { AppFooter } from '@/components/layout/app-footer';
import { AppSidebar } from '@/components/layout/app-sidebar';
import { SidebarProvider, SidebarTrigger } from '@/components/shadcn-ui/sidebar';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <main className='flex h-[calc(100vh-56px)] w-full flex-col gap-2 p-2 md:h-auto'>
            <SidebarTrigger className='hidden md:flex' />
            {children}
          </main>
          <AppFooter className='flex md:hidden' />
        </SidebarProvider>
      </body>
    </html>
  );
}
